modLoader = "javafml"
loaderVersion = "[46,)"
license = "CC BY-NC-ND 4.0"

[[mods]]
modId = "earthtojavamobs"
version = "${modVersion}"
displayName = "Earth2Java"
authors = "Slexom"
description = "Bring mobs from Minecraft Earth to Minecraft Java Edition"
logoFile = "icon.png"

[[dependencies.earthtojavamobs]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.earthtojavamobs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.earthtojavamobs]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"