modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="earthtojavamobs"
version="1.0.0"
displayName="Earth2JavaMobs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="bcarm, MCreator"

[[dependencies.earthtojavamobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



