modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="earthtojavamobs"
version="1.0.0"
displayName="Earth2JavaMobs"
credits="Slexom"
authors="Slexom"
logoFile="logo.png"

[[dependencies.earthtojavamobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



